#!/bin/bash

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# CHANGING APACHE NIFI CONFIG FILE
#=================================================
if [[ "$new_path" != "/" ]];then
    ynh_delete_file_checksum --file="$install_dir/conf/nifi.properties"
    ynh_replace --match="$old_domain" --replace="$new_domain" --file="$install_dir/conf/nifi.properties"
    ynh_replace --match="nifi.web.context.path=$old_path" --replace="nifi.web.context.path=$new_path" --file="$install_dir/conf/nifi.properties"
    ynh_store_file_checksum $install_dir/conf/nifi.properties
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
