#!/bin/bash

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# CHANGING METABASE CONFIG FILE
#=================================================
ynh_delete_file_checksum --file="install_dir/conf/nifi.properties"
ynh_config_add --template="nifi.properties" --destination="$install_dir/conf/nifi.properties"

ynh_delete_file_checksum --file="$install_dir/conf/login-identity-providers.xml"
ynh_config_add --template="login-identity-providers.xml" --destination="$install_dir/conf/login-identity-providers.xml"

ynh_delete_file_checksum --file="$install_dir/conf/authorizers.xml"
ynh_config_add --template="authorizers.xml" --destination="$install_dir/conf/authorizers.xml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
