#!/bin/bash

#=================================================
# BUTTON ACTION
#=================================================
run__install_keystore() {
    if [ -f "$install_dir/conf/keystore.jks" ]; then
        rm $install_dir/conf/keystore.jks
    fi

    keytool -genkeypair -alias nifi -keyalg RSA -keystore $install_dir/conf/keystore.jks -storepass $keystorepasswd -keypass $keystorepasswd -validity 365 -keysize 2048 -dname "CN=$domain,OU=users"
}

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source /usr/share/yunohost/helpers
source _common.sh

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
ynh_app_config_run "$1"