#!/bin/bash

#=================================================
# BUTTON ACTION
#=================================================
run__install_keystore() {
    install_dir=$(ynh_app_setting_get --key=install_dir)

    __install_keystore $install_dir    
}

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

