#!/bin/bash

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# INSTALL JAVA SE 21 if chosen 
#=================================================
ynh_script_progression "Checking up source if needed..."

if [ ! -d "$java_home" ]; then
  mkdir $java_home
  ynh_setup_source --dest_dir="$java_home" --source_id="java21"
fi


#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="main"

chmod +x $install_dir/bin/nifi.sh
chmod +x $install_dir/bin/nifi-env.sh

#=================================================
# SETUP ENVIRONNEMENT
#=================================================

ynh_replace_regex --match="#export JAVA_HOME.*" --replace="export JAVA_HOME=$java_home" --file="$install_dir/bin/nifi-env.sh"

__install_keystore $install_dir

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Data processing tool" --log="/var/log/$app/$app.log"

#=================================================
# SETUP CONFIG
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="nifi.properties" --destination="$install_dir/conf/nifi.properties"
ynh_config_add --template="login-identity-providers.xml" --destination="$install_dir/conf/login-identity-providers.xml"
ynh_config_add --template="authorizers.xml" --destination="$install_dir/conf/authorizers.xml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
#ynh_script_progression "Starting $app's systemd service..."

ynh_exec_as_app $install_dir/bin/nifi.sh set-single-user-credentials $mainadmin $mainpassword

ynh_systemctl --service=$app --action=start --log_path=systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
